### PR TITLE
Add compatibility note to mysql sidecar README

### PR DESCRIPTION
**Pull request by HartS**

### CODE REVIEW

**Comment by mook-as** [comment]
We might want to drop a reference to the underlying issue, https://github.com/go-sql-driver/mysql/issues/785

**Review by mook-as — CHANGES_REQUESTED** [review]
(See comments)

**Comment by HartS** [comment]
@mook-as this is done now

**Review by mook-as — APPROVED** [review]
Looks like [`go-sql-driver/mysql` 1.4.0](https://github.com/go-sql-driver/mysql/releases/tag/v1.4.0) fixes this; we need to bump the vendored package to get the fix.  In the mean time, we can merge this.

**Pull request merged**
